# Generated by Django 4.1 on 2022-08-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_alter_question_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='top_fixed',
            field=models.BooleanField(default=False, verbose_name='상단고정'),
        ),
        migrations.AddField(
            model_name='question',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
