# Generated by Django 4.1 on 2022-09-02 08:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_question_top_fixed_question_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
