# Generated by Django 4.1 on 2022-09-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0014_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
